### ISSUE TITLE
Feature wishlist

### ISSUE THREAD

**Issue by tomasaschan** [JuliaMath/Interpolations.jl#5]
Now that basic functionality is in place, we need to extend what we have with more cases, to make the library feature complete. That's a good case for a wishlist =) This issue is intended to keep track of overall progress toward feature parity with (interpolation parts of) Grid.jl - actual implementation details can be discussed in separate issues.

**Boundary condtions** (assuming a grid on `1:n`)
- [x] `Flat`, i.e. `f'(x=1) = f'(x=n) = 0` (#8)
- [x] `Line` (or `Natural`), i.e. `f''(x=1) = f''(x=n) = 0` (#9)
- [ ] `Tangent`, i.e. with specified derivatives at the edges (`Flat` is essentially `Tangent(0,0)`)
- [x] `Reflect`, i.e. _all_ continuous derivatives are 0 at the edge, to preserve continuity properties when extrapolating (Added in #20)
- [x] `Periodic`, i.e. function value and all derivatives are equal at both edges; with `OnGrid`, the data should include both cell boundaries (and `A[1]==A[end]`), while with `OnCell` this assumption is not necessary (but rather `A[-.5] == A[end+.5]`) (#9)
- [x] `Free`, i.e. with extra continuous derivatives close to the edges, to close the system. (For e.g. cubic splines, which have continuous second derivatives, the third derivatives are also continuous at the second-to-last boundaries). (#9)

**Extrapolation behaviors**
- [x] `Constant`, i.e. return the value at the closest data point (#8)
- [x] `Linear` (#23)
- [ ] `Quadratic` etc, valid up to the same degree as the interpolation. When the same degree, just continue the outermost polynomial; when lower degree, construct an extrapolation polynomial with as many continuous derivatives as necessary for a smooth transition. For example, linear extrapolation of a quadratic interpolation object, would have continuous value and first derivative (which conveniently specifies the extrapolation uniquely...).
- [x] `Periodic`, i.e. `f(x + T) = f(x)` for a function with period `T` (#9)
- [x] `Reflec`, i.e. `f(end - 1 + T/3) = f(end - T/3 + 1)` (#9)

**Interpolation degrees**
- [x] Cubic b-splines (#90 - thanks @spencerlyon2!)

**Other functionality**
- [x] Derivative evaluation, up to the highest continuous degree supported by the interpolation object. E.g. `gradient(itp::Quadratic, x)` or `hessian(itp::Cubic, x)`. (Gradient fixed in #18, higher orders will be added when higher order interpolations are added...)
- [x] Multi-valued interpolation (i.e. interpolation that yields more than one value per coordinate), More of a decision: do we do anything special to make it easier, or just force users to shape their data accordingly? Discussed separately under #3 
- [x] Range/vector-valued indexing (i.e. indexing with multiple values at the same time, e.g. `itp[1:.1:10]`) (#24, #54, #55)
- [x] Non-uniform interpolation (#11, #56)
- [x] Uniform interpolation on non-unit scales (the same problem that `CoordInterpGrid` in `Grid.jl` solves) (#25, #47)

**Comment by kzapfe** [comment]
I have some of a theorical/implementation question:
Why packages such as Pyplot have such a large set of interpolation routines to plot functions over 2D domains ("images") and on the other hand turns out to be so cumbersome to implement the same interpolations "just to the data"? What I am missing here? 
I think I have the same problem as other people here: I need continous, reliable Hessians for my work. I see what can I understand of your package and see if I can contribute. Keep the splendid work!

**Comment by tlycken** [comment]
@kzapfe PyCall/PyPlot are of a very specific type of Julia packages - they're both wrappers for code in other languages that have had much more time than Julia to evolve and mature. Thus, comparison to pure Julia packages like Interpolations.jl isn't quite "fair" to either type of package. Since PyPlot is built specifically for showing things on-screen, it's maybe not so surprising that it focuses its efforts on 2D. Did you have any other packages with the same limitations in mind? 

It's also a much larger problem to write general code that works in any number of dimensions than to write for just one case, so if you only need 1D and 2D there's no reason to build something more general. 

That said, you can probably find a lot of good interpolation code in various languages that already has been/would be easy enough to wrap in Julia and that does what you need. 

My ambition with this library is to, eventually, eliminate the need for calling out to other languages, at least if you don't need something very specific - but part of the reason for building it is to have an excuse to practice Julia programming :)

**Comment by abahm** [comment]
This looks great - thanks for all your work!   I'm looking at a task that would require [barycentric Lagrange interpolation](https://en.wikipedia.org/wiki/Lagrange_polynomial#Barycentric_interpolation), which might fit here.  Is anyone already working on this?

**Comment by tlycken** [comment]
@abahm Not that I know of. If you feel up to it, a PR is always welcome :) The API should probably be something like that for gridded interpolation, e.g. `interpolate(knots, data, Lagrange)` or even `interpolate(knots, data, Lagrange(Barycentric))` to make room for regular Lagrange interpolation too.

**Comment by spencerlyon2** [comment]
I'm going to try to get my hands dirty with cubic splines! I might reach out for help if I get stuck, hope you don't mind!

**Comment by spencerlyon2** [comment]
Also, as I go would you be OK with me trying my best to add docstrings to currently undocumented functions? That would help me learn what everything does.

**Comment by tlycken** [comment]
@spencerlyon2 Great! I'm really excited about this project :)

Docstrings are great (we have already discussed moving most of the documentation into them, and away from the Readme, see #46) - but you might also find the documentation in [`doc/latex`](https://github.com/tlycken/Interpolations.jl/tree/master/doc/latex) useful when figuring out how the current B-spline functionality fits together. I'd love if you could add a few sections for the cubic spline interpolation as well (you can probably copy most of the text, and just update the matrix equations).

My main concerns with this library is that the API stays consistent, and keeps leaving room for incorporating new interpolation schemes, and that we ensure that the composability that we have between the current implementations of b-splines, extrapolation and scaling, is kept for other schemes as well. Together with Tim's focus on squeezing out every single ounce of performance I really think we've found a sweet spot :) I have the ambition of helping you shape your contributions to fit well into this framework. I'm telling you this to make it clear from the start that I do value your contributions - and then I hope you'll have some patience if I'm nit-picky sometimes in my code review... ;)

Feel free to file issues with questions whenever you need it - we'll do our best to answer them promptly.

**Comment by timholy** [comment]
Yeah, this sounds fantastic. Do shout for help if you find any of the metaprogramming-heavy stuff confusing.

**Comment by fabgrei** [comment]
Is there a way of performing cubic spline interpolation on a non-uniform grid with this package?

If no, is there a specific reason? It seems to me that the generalization from uniform grid to a non-uniform should be independent of the uniform interpolation scheme.

My workaround so far looks like

```julia
function itp_nonuniform(val::Real, itp_uniform, x, y)
    i = 2
    while val > x[i]
        i += 1
    end
    λ = (val - x[i-1])/(x[i] - x[i-1])

    itp_uniform[i - 1 + λ]
end

itp_nonuniform(vals::AbstractVector, itp_uniform, x, y) =
    broadcast(val -> itp_nonuniform(val, itp_uniform, x, y), vals)
```

Some illustration
```julia
using Interpolations, Plots

N = 40
xmax = 2*round(π, 4)

x = xmax * [0; sort(rand(N-2)); 1]
y = sin.(x)

itp_uniform = interpolate(y, BSpline(Cubic(Natural())), OnGrid())

scatter(x, y, label="true")
vals = linspace(0, xmax, 5*N)
plot!(vals, itp_nonuniform(vals, itp_uniform, x, y), label="interp")
```

**Comment by dagap** [comment]
One thing that would be nice to have is also sinc interpolation.

**Comment by sglyon** [comment]
Thanks @dagap I've opened a separate issue #145

**Comment by babaq** [comment]
i wish this package include smooth splines too. recently i tried to convert some R code to Julia which uses R smooth.spline function. The Dierckx.jl can do smooth spline, but the only parameters is a smoothness. R version accept degree of freedoms which is very useful to control not only smoothness but also the complexity of the spline. right now i am using RCall, but hope to replace the hack some day.

another thought is why not use callable overload to sugar coat the interpolation. Dierckx.jl makes the splines callable, so instead of `s[newx]`, i found it more natural to consider the splines as a function `s(newx)`  since most of the time, we use it to fit a smooth functions. of course, this can be added easily, is there any confusions were both be added?

**Comment by PallHaraldsson** [comment]
@gerlero Should monotonic, i.e. https://github.com/gerlero/PCHIPInterpolation.jl be on the list here?

I used PCHIP from SciPy at the time when I needed it (and extrapolation) and it wasn't then available in Julia (when porting from MATLAB). Maybe it makes sense to add that package as a dependency (I believe its BSD license may be compatible with MIT here), not to reimplement. If not add it as a forth alternative in the README?

**Comment by mkitti** [comment]
> be on the list here

No. Please create a new issue.

**Comment by PallHaraldsson** [comment]
I rather just added a doc to README #493, at least for now. Did you for sure mean to close since 2 of the tasks not yet completed?
